- .github/scripts/install-helm-chart.sh
- .github/scripts/test-helm-release.sh
- .github/workflows/test.yml
- api/kubernetes/helm-chart/templates/tests/test-connection.yaml
- [helm] Fix command for testing an Helm Release
- chore(CI): Add CI Job for deploying the Helm Chart to a local KinD Cluster and testing it
> CI: Test our Helm Chart

- scenario/src/main/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImpl.kt
- scenario/src/main/openapi/scenarios.yaml
- scenario/src/test/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImplTests.kt
See https://spaceport.cosmotech.com/jira/browse/PROD-7687
> [PROD-7687] Initialize Child Scenario Parameters values with the parent ones, if any

- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/ContainerFactory.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/SolutionContainerStepSpec.kt
- scenariorun/src/test/kotlin/com/cosmotech/scenariorun/ContainerFactoryTests.kt
- solution/src/main/kotlin/com/cosmotech/solution/utils/SolutionUtils.kt
run template id was not in the build storage path for step zip file.
> runTemplateId in cloud storage path for run template zip resources

- api/src/main/resources/application.yml
- common/src/main/kotlin/com/cosmotech/api/config/CsmPlatformProperties.kt
- connector/src/main/openapi/connectors.yaml
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/ContainerFactory.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/workflow/argo/ArgoWorkflowService.kt
- scenariorun/src/main/openapi/scenarioruns.yaml
- scenariorun/src/test/kotlin/com/cosmotech/scenariorun/ContainerFactoryTests.kt
- scenariorun/src/test/kotlin/com/cosmotech/scenariorun/workflow/argo/ArgoWorkflowServiceTests.kt
Option in connector: azureManagedIdentity
=> labels in containers with aadpodidbinding value set to config platform.azure.credentials.aadpodidbinding
=> env var CSM_AZURE_MANAGED_IDENTITY set to "true"
> Aadpodbinding AKS Pod Managed Identity

- api/kubernetes/deploy_release.template.sh
- api/kubernetes/deploy_via_helm.sh
- api/kubernetes/helm-chart/values-dev.yaml
set ingress annotations for https://spaceport.cosmotech.com/jira/browse/PROD-7741
> default global max body size infinite

- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/ContainerFactory.kt
- scenariorun/src/test/kotlin/com/cosmotech/scenariorun/ContainerFactoryTests.kt
free some event hubs before refactoring of event hub usage
> Remove event bus -scenarioruns control place

- .detekt/detekt.yaml
- api/src/main/resources/application.yml
- common/src/main/kotlin/com/cosmotech/api/config/CsmPlatformProperties.kt
- common/src/main/kotlin/com/cosmotech/api/events/CsmRequestResponseEvents.kt
- scenario/src/main/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImpl.kt
- scenario/src/main/openapi/scenarios.yaml
- scenario/src/test/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImplTests.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/ContainerFactory.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/azure/ScenarioRunServiceImpl.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/workflow/WorkflowService.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/workflow/argo/ArgoWorkflowService.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/workflow/argo/WorkflowBuilders.kt
- scenariorun/src/main/openapi/scenarioruns.yaml
- scenariorun/src/test/kotlin/com/cosmotech/scenariorun/workflow/argo/WorkflowBuildersTests.kt
- solution/src/main/openapi/solutions.yaml
- [PROD-7973] Add scenariodata_transform source
- [PROD-7973] Add endpoint for scenario data download management
- [PROD-7973] Implement scenario data download management
- [PROD-7973] Add call to scenario data upload container
- [PROD-7973] Allow to declare artifacts in ScenarioRunContainer
- [PROD-7973] Use scenariodata as container blob prefix
- [PROD-7973] Add job id to the Workflow labels
- [PROD-7973] Log scenario data download response
- [PROD-7973] Retrieve job status and download URL artifact
> [PROD-7973] Download Scenario Data

- doc/Apis/SolutionApi.md
- doc/README.md
- solution/src/main/kotlin/com/cosmotech/solution/azure/SolutionServiceImpl.kt
- solution/src/main/openapi/solutions.yaml
endpoint to download a run template with spring boot starter for Azure storage
> download handler. Factorization of run template validation

- dataset/src/main/kotlin/com/cosmotech/dataset/azure/DatasetServiceImpl.kt
- dataset/src/main/openapi/datasets.yaml
- doc/.openapi-generator/FILES
- doc/Apis/DatasetApi.md
- doc/README.md
- openapi/plantuml/schemas.plantuml
mandatory tag list parameter
AND operator
> Search dataset by tag

- common/id/src/main/kotlin/com/cosmotech/api/id/hashids/HashidsCsmIdGenerator.kt
- common/id/src/test/kotlin/com/cosmotech/api/id/hashids/HashidsCsmIdGeneratorTests.kt
The error below is returned otherwise:
```
number cannot be greater than 9007199254740992L
```
> [PROD-8703] Fix error when number to encode as hashid is higher than the max allowed

- api/kubernetes/upgrade.sh
distinguish git branch. Only upgrade version is necessary. fix issue with jq null value
> simpler script

- .detekt/detekt.yaml
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/ContainerFactory.kt
- solution/src/main/openapi/solution.yaml
please don't forget the branch 'use_github_as_source_for_solution_run_template_PROD-8608' in css
> [PROD-8608] Add the ability to use github as source for the run template

- api/kubernetes/helm-chart/values.yaml
> add storageclass tags

- api/src/main/resources/application.yml
- build.gradle.kts
The spring configuration part to have metrics exposed for services endpoint with common tags
> add spring metrics configuration

- doc/Apis/OrganizationApi.md
- doc/Apis/ScenarioApi.md
- doc/Apis/WorkspaceApi.md
- doc/README.md
- organization/src/main/openapi/organization.yaml
- scenario/src/main/openapi/scenario.yaml
- workspace/src/main/openapi/workspace.yaml
I fixed a couple of typos and did some style adjustments on the permission API
> typos and summary style

- doc/Apis/OrganizationApi.md
- doc/Apis/ScenarioApi.md
- doc/Apis/WorkspaceApi.md
- doc/README.md
- organization/build.gradle.kts
- organization/src/main/kotlin/com/cosmotech/organization/azure/OrganizationServiceImpl.kt
- organization/src/main/openapi/organization.yaml
- organization/src/test/kotlin/com/cosmotech/organization/azure/OrganizationServiceImplTests.kt
- scenario/src/main/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImpl.kt
- scenario/src/main/openapi/scenario.yaml
- workspace/src/main/kotlin/com/cosmotech/workspace/azure/WorkspaceServiceImpl.kt
- workspace/src/main/openapi/workspace.yaml
AccessControl Patch endpoints for 3 components:
- Organization
- Workspace
- Scenario
> Patch endpoint for AccessControl

- doc/Apis/OrganizationApi.md
- doc/README.md
- organization/src/main/kotlin/com/cosmotech/organization/azure/OrganizationServiceImpl.kt
- organization/src/test/kotlin/com/cosmotech/organization/azure/OrganizationServiceImplTests.kt
- scenario/src/main/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImpl.kt
- workspace/src/main/kotlin/com/cosmotech/workspace/azure/WorkspaceServiceImpl.kt
implementaion of addUserRole in 2 components: Workspace & Scenario
Organization not needs it because of it parent nature
> adding parent user list control

- doc/Apis/OrganizationApi.md
- doc/README.md
- organization/src/main/kotlin/com/cosmotech/organization/azure/OrganizationServiceImpl.kt
- scenario/src/main/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImpl.kt
- scenario/src/test/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImplTests.kt
- workspace/src/main/kotlin/com/cosmotech/workspace/azure/WorkspaceServiceImpl.kt
> ACL SQL update

- organization/src/main/kotlin/com/cosmotech/organization/azure/OrganizationServiceImpl.kt
- scenario/src/main/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImpl.kt
- workspace/src/main/kotlin/com/cosmotech/workspace/azure/WorkspaceServiceImpl.kt
Fix Cast error when security null
> Security cast error when null

- build.gradle.kts
- doc/Apis/TwingraphApi.md
- doc/README.md
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/ContainerFactory.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/azure/ScenarioRunServiceImpl.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/workflow/WorkflowService.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/workflow/argo/ArgoWorkflowService.kt
- twingraph/src/main/kotlin/com/cosmotech/twingraph/api/TwingraphServiceImpl.kt
- twingraph/src/main/openapi/twingraph.yaml
Add /organizations/{organization_id}/job/{job_id}/status endpoint 
Add service implementation and event management
Add findWorkflowStatusByLabel method to retrieve workflow only by label
> Define and implement import job status endpoint for twingraph

- api/src/main/resources/application.yml
- build.gradle.kts
- solution/src/main/kotlin/com/cosmotech/solution/azure/SolutionServiceImpl.kt
- workspace/src/main/kotlin/com/cosmotech/workspace/azure/WorkspaceServiceImpl.kt
- workspace/src/test/kotlin/com/cosmotech/workspace/azure/WorkspaceServiceImplTests.kt
workspace file upload
solution handler upload
> Filetypecheck

- api/src/main/resources/application.yml
- build.gradle.kts
- doc/.openapi-generator/FILES
- doc/Models/SourceInfo.md
- doc/Models/TwinGraphImport.md
- doc/README.md
- openapi/plantuml/schemas.plantuml
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/azure/ScenarioRunServiceImpl.kt
- twingraph/src/main/kotlin/com/cosmotech/twingraph/api/TwingraphServiceImpl.kt
- twingraph/src/main/openapi/twingraph.yaml
Change TwinGraphImport structure (endpoint body)
Add Storage-> TwinGraph container
Add mapping between source types and containers
> Modify TwingraphImport endpoint

- .github/workflows/build_test_package.yml
- api/src/main/resources/application.yml
- build.gradle.kts
Bump cosmotech api azure 0.1.19 (no more ADX ingest client)
> Bump cosmotech api azure 0.1.1

- doc/.openapi-generator/FILES
- doc/Apis/TwingraphApi.md
- doc/Models/TwinGraphHash.md
- doc/README.md
- openapi/plantuml/schemas.plantuml
- twingraph/src/main/kotlin/com/cosmotech/twingraph/api/TwingraphServiceImpl.kt
- twingraph/src/main/openapi/twingraph.yaml
- twingraph/src/test/kotlin/com/cosmotech/twingraph/api/TwingraphServiceImplTests.kt
2 endpoints for bulk querying in async way
Data is stored in Redis for 24h. If the same request made on same data version and data exists in Redis, it's returned.
> Mass query

- api/src/main/resources/application.yml
- twingraph/src/main/kotlin/com/cosmotech/twingraph/extension/Twingraph.ext.kt
- twingraph/src/test/kotlin/com/cosmotech/twingraph/utils/TwingraphExtTests.kt
null are return as is and send in json response as null json value
> fix null value processing in redis query resultset

- .github/workflows/deploy.yml
- .github/workflows/deploy_staging.yml
dev platform will have for example:
/ : cosmotech-api-latest (main)
/v2.4-dev : cosmotech-api-v2.4-dev (dev)
/v2.3: cosmotech-api-v2.3 (GA)
Staging will have:
/ : 404
/v2.5-preview : cosmotech-api-v2.4-preview (private preview)
/V2.4-public : cosmotech-api-v2.5-public (public preview)
/v2.3 : cosmotech-api-v2.3 (GA)
> Github Workflow release process CD

- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/ContainerFactory.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/workflow/argo/ArgoWorkflowService.kt
- scenariorun/src/main/openapi/scenariorun.yaml
See comments in the ticket in order to test
> Use scenario's runSizing if provided to run a scenario

- openapi/example_files/Brewery_Solution.yaml
- solution/src/main/openapi/solution.yaml
Fix typo in Cosmo-Tech and use the correct repo name
> Fix brewery URL in examples

- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/service/ScenarioRunServiceImpl.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/workflow/argo/ArgoWorkflowService.kt
Force the scenario, scenariorun state to failed
> Hack due to Argo workflows not stopping

- dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceIntegrationTest.kt
- dataset/src/main/kotlin/com/cosmotech/dataset/service/DatasetServiceImpl.kt
prevent falling in source!! error. also prevent NONE type refresh
> add default value for dataset.source

- dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceIntegrationTest.kt
- dataset/src/main/kotlin/com/cosmotech/dataset/service/DatasetServiceImpl.kt
- dataset/src/main/kotlin/com/cosmotech/dataset/utils/Twingraph.ext.kt
- dataset/src/test/kotlin/com/cosmotech/dataset/service/DatasetServiceImplTests.kt
fix test on async sub dataset create
dataset was pending with no jobId. return status on no jobId
> fix import by removing removal of id property

- dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceIntegrationTest.kt
- dataset/src/main/kotlin/com/cosmotech/dataset/service/DatasetServiceImpl.kt
trx function save dataset modification, this case all modification of parent dataset to be persisted
> fix: remove apply on dataset parent connector on sub create

- doc/.openapi-generator/FILES
- doc/Apis/OrganizationApi.md
- doc/Models/Organization.md
- doc/README.md
- openapi/plantuml/schemas.plantuml
- organization/src/integrationTest/kotlin/com/cosmotech/organization/service/OrganizationServiceIntegrationTest.kt
- organization/src/integrationTest/kotlin/com/cosmotech/organization/service/OrganizationServiceRBACTest.kt
- organization/src/main/kotlin/com/cosmotech/organization/service/OrganizationServiceImpl.kt
- organization/src/main/openapi/organization.yaml
- organization/src/test/kotlin/com/cosmotech/organization/service/OrganizationServiceImplTests.kt
These information are not actually used, we only use the properties/values from the config
> Remove organization services configuration

- workspace/src/integrationTest/kotlin/com/cosmotech/workspace/service/WorkspaceServiceRBACTest.kt
- workspace/src/main/kotlin/com/cosmotech/workspace/service/WorkspaceServiceImpl.kt
- workspace/src/test/kotlin/com/cosmotech/workspace/service/WorkspaceServiceImplTests.kt
S3Template seems to be limited/bugged and only returns the first page, directly use S3Client to properly list all objects.
> Correctly list all S3 objects using the paging API

- build.gradle.kts
- run/src/main/kotlin/com/cosmotech/run/exceptions/RunExceptionHandling.kt
Upgrade module com.fasterxml.jackson.module:jackson-module-kotlin to 2.17.2 version
> Add GlobalExceptionHandler

- .github/workflows/openapi_clients.yml
- README.md
- api/build.gradle.kts
- scripts/clients/publish_client.sh
These are not used or fully tested
> Remove the Javascript, Java and C# clients

- .github/workflows/build_test_package.yml
- .github/workflows/doc.yml
- .github/workflows/lint.yml
- .github/workflows/openapi.yml
- .github/workflows/openapi_clients.yml
- run/src/integrationTest/kotlin/com/cosmotech/run/service/RunServiceIntegrationTest.kt
- run/src/main/kotlin/com/cosmotech/run/RunApiServiceInterface.kt
- run/src/main/kotlin/com/cosmotech/run/RunEventServiceInterface.kt
- run/src/main/kotlin/com/cosmotech/run/service/RunEventServiceImpl.kt
- run/src/main/kotlin/com/cosmotech/run/service/RunServiceImpl.kt
- runner/src/integrationTest/kotlin/com/cosmotech/runner/service/RunnerServiceIntegrationTest.kt
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerApiServiceImpl.kt
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerService.kt
* Check all runs for running state
* Delete runs when deleting a runner
* Clear Runner.lastRunId when the associated run is delete
> Improve runner delete behavior

- api/kubernetes/helm-chart/Chart.yaml
- api/kubernetes/helm-chart/templates/_helpers.tpl
- api/kubernetes/helm-chart/templates/deployment.yaml
- api/kubernetes/helm-chart/values.yaml
- api/src/integrationTest/resources/application-test.yml
- api/src/main/resources/application.yml
- build.gradle.kts
- connector/src/integrationTest/resources/application-connector-test.yml
- dataset/src/integrationTest/resources/application-dataset-test.yml
- organization/src/integrationTest/resources/application-organization-test.yml
- run/src/integrationTest/resources/application-run-test.yml
- runner/src/integrationTest/resources/application-runner-test.yml
- solution/src/integrationTest/resources/application-solution-test.yml
- workspace/src/integrationTest/resources/application-workspace-test.yml
New cosmotech configuration and helm chart for client side trust store SSL bundle definition and integration in redis client.
> REDIS TLS feature with custom SSL bundle to custom root certificate

- runner/src/integrationTest/kotlin/com/cosmotech/runner/service/RunnerServiceIntegrationTest.kt
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerService.kt
https://cosmo-tech.atlassian.net/browse/SDCOSMO-1936
> fix list runner when rbac is off

- runner/src/integrationTest/kotlin/com/cosmotech/runner/service/RunnerServiceIntegrationTest.kt
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerService.kt
Update `Runner.parentId` to point to grand parent or null when parent is deleted
> Update runner parentId on parent deletion

- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/ContainerFactory.kt
Fix error 500 when a scenario parameter %DATASET_ID% is empty
> [PROD-14190]  "Dataset  cannot be found in Datasets" 

- connector/src/main/openapi/connector.yaml
- dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceIntegrationTest.kt
- dataset/src/main/kotlin/com/cosmotech/dataset/service/DatasetServiceImpl.kt
- dataset/src/main/openapi/dataset.yaml
- dataset/src/test/kotlin/com/cosmotech/dataset/service/DatasetServiceImplTests.kt
- doc/.openapi-generator/FILES
- doc/Apis/ConnectorApi.md
- doc/Apis/DatasetApi.md
- doc/Apis/OrganizationApi.md
- doc/Apis/RunApi.md
- doc/Apis/RunnerApi.md
- doc/Apis/SolutionApi.md
- doc/Apis/WorkspaceApi.md
- doc/Models/SendRunDataRequest.md
- doc/README.md
- organization/src/main/openapi/organization.yaml
- run/src/main/openapi/run.yaml
- runner/src/main/openapi/runner.yaml
- solution/src/main/openapi/solution.yaml
- workspace/src/main/openapi/workspace.yaml
Make sure we have both support everywhere and that they take the same schemas
> Support JSON and YAML as input and output of the API

- sonar-project.properties
Select directories to be excluded from SonarQube analysis
> feat: configure static code analyzer

- LICENSE
- README.md
- api/build.gradle.kts
- api/src/main/resources/banner.txt
- build.gradle.kts
- connector/build.gradle.kts
- dataset/build.gradle.kts
- dataset/src/main/kotlin/com/cosmotech/dataset/service/DatasetServiceImpl.kt
- doc/Models/SendRunDataRequest.md
- metrics/src/main/kotlin/com/cosmotech/metrics/MetricsServiceImpl.kt
- openapi/plantuml/schemas.plantuml
- organization/build.gradle.kts
- organization/src/main/kotlin/com/cosmotech/organization/service/OrganizationServiceImpl.kt
- run/build.gradle.kts
- run/src/main/kotlin/com/cosmotech/run/RunContainerFactory.kt
- run/src/main/kotlin/com/cosmotech/run/service/RunServiceImpl.kt
- run/src/main/kotlin/com/cosmotech/run/service/amqp/AmqpClientServiceImpl.kt
- run/src/main/kotlin/com/cosmotech/run/workflow/argo/RunArgoWorkflowService.kt
- run/src/main/openapi/run.yaml
- runner/build.gradle.kts
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerApiServiceImpl.kt
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerService.kt
- scripts/clients/build_override/LICENSE
- solution/build.gradle.kts
- solution/src/main/kotlin/com/cosmotech/solution/service/SolutionServiceImpl.kt
- solution/src/main/openapi/solution.yaml
- workspace/build.gradle.kts
- workspace/src/main/kotlin/com/cosmotech/workspace/service/WorkspaceServiceImpl.kt
- remove harcoded versions in build.gradle.kts files
- merge into allProjects dependencies, redundant dependencies of all sub-projects
- replace if/checks by require/check/requireNotNull
- code Cleaning (naming,...)
> Sustaining based on SonarQube warnings

- run/src/main/kotlin/com/cosmotech/run/metrics/RunMetrics.kt
As we rework the metric system, we can remove the scheduled tasks that push argo running workflows in Redis TS. Charts will be based on Argo metrics exposed in prometheus
> [PROD-14295] Monitoring
