Cosmo-Tech/cosmotech-api

- scenario/src/main/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImpl.kt
- scenario/src/main/openapi/scenarios.yaml
- scenario/src/test/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImplTests.kt
This fixes [PROD-7888](https://spaceport.cosmotech.com/jira/browse/PROD-7888) by introducing a new `Unknown` state for Scenarios, used to handle cases where the status returned by Argo is `null` or not known to us.
There are few cases relevant for this:
- when fetching a scenario right after a successful run request, Argo Server returns a Workflow with a `status` field populated with `null` values, which is returned because the Workflow is about to be scheduled, but is not actually yet. This lasts just few seconds.
- a possible temporary communication error when reaching out to the Scenario Run Service for fetching statuses
> fix(PROD-7888): Map null and un-handled scenario run statuses to a new 'Unknown' Scenario state

- build.gradle.kts
- scenario/src/main/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImpl.kt
- scenario/src/main/openapi/scenarios.yaml
- scenario/src/test/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImplTests.kt
https://spaceport.cosmotech.com/confluence/pages/viewpage.action?pageId=820936776#id-%F0%9F%94%A5WebApp-Scenariomanager-Deletesinglescenario
- when a non-master scenario is deleted, all its direct children scenarios need a new parent. The new parent will be the parent of the deleted scenario. For example, if we have `scenario1 → scenario2 → scenario3` and `scenario2` is deleted, the new tree is `scenario1 → scenario3`.
- when a master is deleted, all its direct children scenarios become master scenarios.
- feat(PROD-7939): Add tests for scenario deletion requirements
- feat(PROD-7939): Introduce a new `wait_relationship_propagation` boolean query parameter to the `DELETE /organizations/:id/scenarios/:id` endpoint
- feat(PROD-7939): Assign a new parent to scenario children after their …
> [PROD-7939] Handle scenario parent-child relationship upon deletion

- api/src/main/resources/application.yml
- common/src/main/kotlin/com/cosmotech/api/config/CsmPlatformProperties.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/ContainerFactory.kt
- scenariorun/src/test/kotlin/com/cosmotech/scenariorun/ContainerFactoryTests.kt
See [1] for the rationale.
Using the core App Registration tenant ID results in "Invalid Issuer"
errors reported by AMQP Consumers at simulation run time.
Using the customer tenant causes other issues as well, as described in
[1].
As a workaround, this adds the ability to authenticate using a configured shared access policy instead.
For now, we leverage the EventHub namespace RootManageSharedAccessKey, but it would ultimately be better to create and use a dedicated one.
[1] https://spaceport.cosmotech.com/jira/browse/PROD-8071
> [PROD-8072] Pass Event Hub Shared Access Policy credentials to solution containers if told so

- build.gradle.kts
- scenario/src/main/kotlin/com/cosmotech/scenario/azure/ScenarioExtensions.kt
- scenario/src/main/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImpl.kt
- scenario/src/main/openapi/scenarios.yaml
- scenario/src/test/kotlin/com/cosmotech/scenario/azure/ScenarioServiceImplTests.kt
- [PROD-8051] Add new 'parentLastRun' and 'rootLastRun' fields to the Scenario API
- [PROD-8051] Add tests for this feature
- [PROD-8051] Make 'findAllScenarios' and 'findScenarioById' methods include info about parent and root last runs
> [PROD-8051] Add info about last runs of Parent and Root to a given child Scenario

- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/ScenarioRunExtensions.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/azure/ScenarioRunServiceImpl.kt
- scenariorun/src/test/kotlin/com/cosmotech/scenariorun/azure/ScenarioRunServiceImplTests.kt
- [PROD-8473] Add tests for all public-facing API endpoints that return ScenarioRuns
- [PROD-8473] Do not dump potentially sensitive container data in ScenarioRun API endpoints
> [PROD-8473] Purposely hide potentially sensitive container data in public-facing ScenarioRun API endpoints

- api/kubernetes/helm-chart/templates/_helpers.tpl
- api/kubernetes/helm-chart/templates/storageclass.yaml
- api/kubernetes/helm-chart/values-azure.yaml
- api/kubernetes/helm-chart/values-dev.yaml
- api/kubernetes/helm-chart/values.yaml
- api/src/main/resources/application.yml
- common/common/src/main/kotlin/com/cosmotech/api/config/CsmPlatformProperties.kt
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/workflow/argo/WorkflowBuilders.kt
- scenariorun/src/test/kotlin/com/cosmotech/scenariorun/workflow/argo/WorkflowBuildersTests.kt
At this time, running a ScenarioRun in a local cluster requires manual changes
to `WorkflowBuilders.kt`, like changing the storage class and storage request
for PVCs used by the ScenarioRun Workflows.
This makes the development experience unpractical.
The changes here make the PVCs options configurable, with sensible defaults
that are backward-compatible.
This is anyway a preliminary step for PROD-8043, which aims at ultimately
being able to specify a local storage class with `ReadWriteMany` access mode
capabilities.
> De-hardcode Workflows Persistent Volume Claims spec building

- build.gradle.kts
There is an issue preventing from running Spotless under Kotlin 1.6.0﻿.
This has been reported in facebookincubator/ktfmt#259.
So we have to wait until this is fixed first.
> Bump Kotlin from 1.5.31 to 1.6.0

- api/src/main/resources/application.yml
- common/azure/src/main/kotlin/com/cosmotech/api/azure/adx/AzureDataExplorerClient.kt
- common/azure/src/test/kotlin/com/cosmotech/api/azure/adx/AzureDataExplorerClientTests.kt
- common/common/src/main/kotlin/com/cosmotech/api/config/CsmPlatformProperties.kt
- doc/Models/RunTemplate.md
- doc/Models/ScenarioRun.md
- doc/Models/Solution.md
- openapi/plantuml/schemas.plantuml
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/azure/ScenarioRunServiceImpl.kt
- scenariorun/src/main/openapi/scenariorun.yaml
- solution/src/main/openapi/solution.yaml
Fix sent messages total when multiple simulations + Race condition on simulation total facts calls:
* noDataTimeOutSeconds API option
* solution.sdkVersion
* runtemplate.noDataIngestionState
> Fix sent messages total when multiple simulations prod 8906

- api/src/main/resources/application.yml
- azstorage-twincache-connector to 1.1.4
- adt-twincache-connector to 0.2.4
> Upgrade version of twingraph injector connector

- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/container/StartInfo.kt
Basic sizing for pods being extremely different between request and limits allowed for strange edge cases, so this PR reduce the difference between those ensuring lower risks during execution.
> Updated default sizing informations for pods

- doc/.openapi-generator/FILES
- doc/Models/RunTemplate.md
- doc/Models/RunTemplateOrchestrator.md
- doc/README.md
- openapi/plantuml/schemas.plantuml
- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/ContainerFactory.kt
- scenariorun/src/test/kotlin/com/cosmotech/scenariorun/ContainerFactoryTests.kt
- scenariorun/src/test/kotlin/com/cosmotech/scenariorun/OktaContainerFactoryTests.kt
- solution/src/main/openapi/solution.yaml
PROD-12221 Support csm-orc in platform API
Definition of Done
When executing a scenario run from API, user can choose between legacy or Python orchestrator
Deployed and tested in phoenixdev
Note
Default behavior to be changed: csm-orc should be the default orchestration mode in API
> Add new orchestrator type to Run Templates

- scenariorun/src/main/kotlin/com/cosmotech/scenariorun/ContainerFactory.kt
csm-orc add a cmd "entrypoint.py" that allow retro compatibility with older docker images
> replaced entrypoint called in all simulator image by "entrypoint.py"

- scenario/src/integrationTest/kotlin/com/cosmotech/scenario/service/ScenarioServiceIntegrationTest.kt
- scenario/src/main/kotlin/com/cosmotech/scenario/service/ScenarioServiceImpl.kt
only delete when dataset create by v3 api. Check with the newly created creationDate property which is null for previous version
> fix dataset deletion on scenario deletion

- api/kubernetes/helm-chart/templates/tests/test-access-openapi.yaml
- api/kubernetes/helm-chart/templates/tests/test-access-swaggerui.yaml
No need to keep successful stopped pods cluttering the cluster
> Clean deploy test pods automatically on success

- dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceIntegrationTest.kt
- dataset/src/main/kotlin/com/cosmotech/dataset/service/DatasetServiceImpl.kt
This come for easing the manipulation of dataset twincache in ETL. Upload can now be done for every sourceType not just File type. Trx (transaction) has been removed from crud for twincache entities.
> remove restriction on dataset twincache manipulation

- dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceIntegrationTest.kt
- dataset/src/main/kotlin/com/cosmotech/dataset/service/DatasetServiceImpl.kt
Redis search have a hard time with dot(.)
> fix generated connector name to simplify redis search

- run/src/main/kotlin/com/cosmotech/run/config/RunStorageConfig.kt
- run/src/main/kotlin/com/cosmotech/run/service/RunServiceImpl.kt
This allow to add runner metadata on the database itself making it easier to debug future issues where only the run id is given
(direct connection to the postgresql instance and use of \l+ will show the comments)
> Add comment on database creation

- api/kubernetes/helm-chart/values.yaml
These are required and need override, but having them here provides documentation
> Add missing required s3 helm values

- dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceIntegrationTest.kt
- dataset/src/main/kotlin/com/cosmotech/dataset/service/DatasetServiceImpl.kt
- dataset/src/main/openapi/dataset.yaml
- doc/Apis/DatasetApi.md
Update return type of `dataset/twingraphQuery` to list
This update allows a cleaner explanation of the return type as Cypher queries return list of results
Also this should update the API libraries generated so that there is no need to do user based operation on the return value.
No more need to convert the returned string to working types using external libraries.
> Return twingraph query results as json list

- build.gradle.kts
- run/src/main/kotlin/com/cosmotech/run/workflow/argo/WorkflowBuilders.kt
- run/src/test/kotlin/com/cosmotech/run/workflow/argo/WorkflowBuildersTests.kt
- workspace/src/main/kotlin/com/cosmotech/workspace/service/WorkspaceServiceImpl.kt
Somehow, the current version was generating timeouts
This will need to be backported to versions 3.2+
> [PROD-13427][PROD-13433] Update k8s client to 21.0.0

- workspace/src/main/kotlin/com/cosmotech/workspace/azure/strategy/WorkspaceEventHubStrategyDedicated.kt
- workspace/src/main/kotlin/com/cosmotech/workspace/utils/WorkspaceUtils.kt
This was missed in the recent commit that changed the secret name pattern
> [PROD-13427][PROD-13433] Use workspace id to read the secret

- api/kubernetes/helm-chart/values-azure.yaml
- api/kubernetes/helm-chart/values-dev.yaml
- api/src/main/resources/application.yml
- run/src/integrationTest/resources/application-run-test.yml
- run/src/main/kotlin/com/cosmotech/run/RunContainerFactory.kt
- run/src/test/kotlin/com/cosmotech/run/ContainerFactoryTests.kt
We need the scheme separate to be able to HTTP query the registry for image existence, but we don't need the scheme for image configuration of the workflow
> Improve usage of container registry config

- connector/src/main/kotlin/com/cosmotech/connector/ConnectorApiServiceInterface.kt
- connector/src/main/kotlin/com/cosmotech/connector/service/ConnectorServiceImpl.kt
- connector/src/main/openapi/connector.yaml
- doc/Apis/ConnectorApi.md
- doc/README.md
'-' and some other symbols need to be escaped properly to work with a searchable redis field. However, this endpoint was only added to support a previous migration script and is only used once internally. The internal use does not require this to be a proper endpoint, so we can just make it a method. And the internal use will always look for a fixed connector name that does not exhibit the original search issue.
> [PROD-13480] Remove the 'findConnectorByName' endpoint

- api/kubernetes/helm-chart/README.md
- api/kubernetes/helm-chart/values.yaml
With the new orchestrator we only have a single pod now, so 'Many' access is not required anymore, this should fix azure deployement where we don't force a 'Many' compatible storage anymore
> Fix argo volume access mode

- api/src/main/resources/application.yml
Disable code scanning, it conflicts with our own merge spec config
> Fix swagger-ui spec display/config

- connector/src/main/openapi/connector.yaml
- dataset/src/main/openapi/dataset.yaml
- doc/Apis/ConnectorApi.md
- doc/Apis/DatasetApi.md
- doc/Apis/OrganizationApi.md
- doc/Apis/RunApi.md
- doc/Apis/RunnerApi.md
- doc/Apis/SolutionApi.md
- doc/Apis/WorkspaceApi.md
- doc/README.md
- organization/src/main/openapi/organization.yaml
- run/src/main/openapi/run.yaml
- runner/src/main/openapi/runner.yaml
- solution/src/main/openapi/solution.yaml
- workspace/src/main/openapi/workspace.yaml
This is required for a proper config of Swagger and the clients
> Put back the OAuth config in the OpenAPI spec

- doc/.openapi-generator/FILES
- doc/Apis/RunnerApi.md
- doc/Models/CreatedRun.md
- doc/README.md
- openapi/plantuml/schemas.plantuml
- runner/src/integrationTest/kotlin/com/cosmotech/runner/service/RunnerServiceIntegrationTest.kt
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerApiServiceImpl.kt
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerEventServiceImpl.kt
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerService.kt
- runner/src/main/openapi/runner.yaml
Ideally we should return a RunInstance but this data obejct is defined in the run openapi, not accessible from the runner one. But having a proper object should ease extension if we need to add more data.
> [PROD-13633] Make startRun return a proper object

- solution/src/integrationTest/kotlin/com/cosmotech/solution/service/SolutionServiceIntegrationTest.kt
- solution/src/main/kotlin/com/cosmotech/solution/service/SolutionServiceImpl.kt
- `runTemplates` property definition on Solution has changed previously:
- `runTemplates` is now required
- default value is `[]`
- `updateSolution` does not exclude `runTemplates` field resulting an update with the `runTemplates` default value (a.k.a `[]`). the value was reset
To resolve this, `runTemplates` property is ignored on `updateSolution` call. RunTemplate associated to a Solution should be updated through `updateSolutionRunTemplate`.
> [PROD-13734] Fix update solution with no runTemplates cause runTemplates reset to empty list

- run/src/main/kotlin/com/cosmotech/run/RunContainerFactory.kt
- run/src/main/kotlin/com/cosmotech/run/workflow/argo/WorkflowBuilders.kt
- run/src/test/kotlin/com/cosmotech/run/ContainerFactoryTests.kt
- run/src/test/kotlin/com/cosmotech/run/workflow/argo/WorkflowBuildersTests.kt
Mount output and temp directory in argo containers to be compatible with k8s secured option securityContext.readOnlyRootFilesystem=true
> Mount output and temp directory in argo containers

- doc/Models/Runner.md
- openapi/plantuml/schemas.plantuml
- runner/src/integrationTest/kotlin/com/cosmotech/runner/service/RunnerServiceIntegrationTest.kt
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerService.kt
- runner/src/main/openapi/runner.yaml
Requiring it breaks the updateRunner endpoint, or at minima forces users to provide that field (with current values) even if that's not the field they want to modify.
This should be fixed in a better way when we find the time to rework the API contract and split the data model for creation, update and reading.
> [PROD-13928] Make Runner.datasetList optional again

- run/build.gradle.kts
- run/src/main/kotlin/com/cosmotech/run/metrics/RunMetrics.kt
- run/src/main/kotlin/com/cosmotech/run/service/RunServiceImpl.kt
- run/src/main/kotlin/com/cosmotech/run/workflow/WorkflowService.kt
- run/src/main/kotlin/com/cosmotech/run/workflow/argo/RunArgoWorkflowService.kt
Since Argo Workflows 3.5, listing workflows will also list archived ones.
See [here](https://argo-workflows.readthedocs.io/en/latest/upgrading/#upgrading-to-v35)
and [here](https://github.com/argoproj/argo-workflows/issues/10781)
and [here](https://github.com/argoproj/argo-workflows/blob/release-3.5/ui/src/models/workflows.ts#L542-L560)
The only way I found to filter archived ones from this list is to filter by following label
If this label is in the workflow's labels => the workflow is archived
If not, the workflow is not archived
> Upgrade argo-client-java from v3.4.3 to v3.5.11

- api/kubernetes/helm-chart/templates/pvc.yaml
This should avoid issues on subsequent chart deployment where the default storage class has been resolved and conflicts with a 'nil' or empty default value
> Only pass the PVC storage class if we have one

- runner/src/integrationTest/kotlin/com/cosmotech/runner/service/RunnerServiceIntegrationTest.kt
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerService.kt
Target fix is to rework the api to remove varType from the input data instead of relying on the buggy readOnly config.
In the mean time, consolidate every varType with the reference value from the solution.
> [PROD-9005] Make sure the parameter's varType are the one from the solution

- build.gradle.kts
- dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceIntegrationTest.kt
- dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceRBACTest.kt
- dataset/src/main/kotlin/com/cosmotech/dataset/service/DatasetServiceImpl.kt
- dataset/src/test/kotlin/com/cosmotech/dataset/service/DatasetServiceImplTests.kt
- organization/src/integrationTest/kotlin/com/cosmotech/organization/service/OrganizationServiceIntegrationTest.kt
- organization/src/integrationTest/kotlin/com/cosmotech/organization/service/OrganizationServiceRBACTest.kt
- organization/src/main/kotlin/com/cosmotech/organization/service/OrganizationServiceImpl.kt
- organization/src/test/kotlin/com/cosmotech/organization/service/OrganizationServiceImplTests.kt
- runner/src/integrationTest/kotlin/com/cosmotech/runner/service/RunnerServiceIntegrationTest.kt
- runner/src/integrationTest/kotlin/com/cosmotech/runner/service/RunnerServiceRBACTest.kt
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerApiServiceImpl.kt
- runner/src/main/kotlin/com/cosmotech/runner/service/RunnerService.kt
- solution/src/integrationTest/kotlin/com/cosmotech/solution/service/SolutionServiceIntegrationTest.kt
- solution/src/integrationTest/kotlin/com/cosmotech/solution/service/SolutionServiceRBACTest.kt
- solution/src/main/kotlin/com/cosmotech/solution/service/SolutionServiceImpl.kt
- workspace/src/integrationTest/kotlin/com/cosmotech/workspace/service/WorkspaceServiceIntegrationTest.kt
- workspace/src/integrationTest/kotlin/com/cosmotech/workspace/service/WorkspaceServiceRBACTest.kt
- workspace/src/main/kotlin/com/cosmotech/workspace/service/WorkspaceServiceImpl.kt
- workspace/src/test/kotlin/com/cosmotech/workspace/service/WorkspaceServiceImplTests.kt
restrict the possibility for the role_viewer to see the details of security
> restrict the possibility for the role_viewer to see the details of security

- README.md
To have a nice list of the licenses we were sending users through the codetabs CORS proxy (https://codetabs.com/).
> fix: Do not trust and send traffic through CORS proxy

- metrics/src/main/kotlin/com/cosmotech/metrics/MetricsServiceImpl.kt
Depending on target deployment environment, Redis TS can have DUPLICATE_POLICY set to BLOCK. Until now, Redis TS created by Cosmotech API relied on target environment (without override the default value) As we log every API calls, when API is flooded, it can lead to HTTP errors 500 when Redis is deployed with DUPLICATE_POLICY set to BLOCK (https://redis.io/docs/latest/develop/data-types/timeseries/configuration/#duplicate_policy).
To prevent that, every Redis TS will be created now with DUPLICATE_POLICY set to MAX. Doing that, will not lead to HTTP 500 error and if X Redis TS will be created with the same timestamp, only the TS with the maximum value will be kept.
Note: You should delete all previously created one. A Redis TS cannot be changed/upgraded
> Force DuplicatePolicy for Redis TS created programmatically by Cosmotech

- metrics/src/main/kotlin/com/cosmotech/metrics/MetricsServiceImpl.kt
Depending on target deployment environment, Redis TS can have DUPLICATE_POLICY set to BLOCK. Until now, Redis TS created by Cosmotech API relied on target environment (without override the default value) As we log every API calls, when API is flooded, it can lead to HTTP errors 500 when Redis is deployed with DUPLICATE_POLICY set to BLOCK (https://redis.io/docs/latest/develop/data-types/timeseries/configuration/#duplicate_policy).
To prevent that, every Redis TS will be created now with DUPLICATE_POLICY set to MAX. Doing that, will not lead to HTTP 500 error and if X Redis TS will be created with the same timestamp, only the TS with the maximum value will be kept.
Note: You should delete all previously created one. A Redis TS cannot be changed/upgraded
> Force DuplicatePolicy for Redis TS created programmatically by Cosmotech API.

- build.gradle.kts
The openapi-generator-gradle-plugin depends has a transitive dependency on com.samskivert:jmustache:1.15, however the .owasp.dependencycheck.gradle.plugin depends on the more recent 1.16 version so when
both plugins are included the generated python code has syntax errors (see bug issue: https://github.com/OpenAPITools/openapi-generator/issues/20375) To avoid this conflict of plugin dependencies we have to force the resolution of dependencies to
keep the old version. Forcing the dependency also introduces some changes in the typescript client, but fortunately these are new lines that do not seem to have an effect
> fix: repair generated python client code

- scripts/clients/build_override/git_push.sh
When copying the generated client code we did not
copy hidden files so the generated github workflow to run the client tests was never activated.
> fix: include all generated client files

- doc/Models/OrganizationUpdateRequest.md
- openapi/plantuml/schemas.plantuml
- organization/src/integrationTest/kotlin/com/cosmotech/organization/service/OrganizationServiceIntegrationTest.kt
- organization/src/main/openapi/organization.yaml
- organization/src/test/kotlin/com/cosmotech/organization/service/OrganizationServiceImplTests.kt
- organization's name is no longer required for updating an organization
- organization's name should have size between 1 and 50 for creation or update
> Add constraints on Organization

- build.gradle.kts
we can bring up the openapi-generator to v.7.10.0 (but not to latest stable 7.11 without breaking things).
With this minor upgrade to 7.10.0 the generated python client has as minimum requirement python 3.8 instead of 3.7. Both 3.7 and 3.8 versions have reached their end-of-life but at least 3.8 is still available in the github ubuntu latest runners. With this minor change we will be able to avoid a failed github action in the generated python client
> fix: upgrade to python > 3.8

- scenario/src/integrationTest/kotlin/com/cosmotech/scenario/service/ScenarioServiceIntegrationTest.kt
- scenario/src/integrationTest/kotlin/com/cosmotech/scenario/service/ScenarioServiceRBACTest.kt
- scenario/src/main/kotlin/com/cosmotech/scenario/service/ScenarioServiceImpl.kt
- Main Dataset linked to a scenario are not modified anymore (except when a user is added into linked Scenario ACL)
- Update and remove a user from a Scenario ACL do not change ACL for linked dataset marked as main
- Not marked dataset are modified to match the linked scenario ACL
Note:
Dataset that are marked as main can be shared between several Scenario, update/remove ACL entries on main dataset lead to permission issues
> Change dataset ACL management when ACL is modified on Scenario

- .github/workflows/build_test_package.yml
- api/src/integrationTest/kotlin/com/cosmotech/api/home/ControllerTestBase.kt
- api/src/integrationTest/kotlin/com/cosmotech/api/home/ControllerTestUtils.kt
- api/src/integrationTest/kotlin/com/cosmotech/api/home/organization/OrganizationConstants.kt
- api/src/integrationTest/kotlin/com/cosmotech/api/home/organization/OrganizationControllerTests.kt
- api/src/integrationTest/kotlin/com/cosmotech/api/home/solution/SolutionConstants.kt
- api/src/integrationTest/kotlin/com/cosmotech/api/home/solution/SolutionControllerTests.kt
- api/src/integrationTest/kotlin/com/cosmotech/api/home/workspace/WorkspaceConstants.kt
- api/src/integrationTest/kotlin/com/cosmotech/api/home/workspace/WorkspaceControllerTests.kt
- api/src/integrationTest/resources/workspace/test.txt
- doc/Apis/OrganizationApi.md
- doc/Models/SolutionUpdateRequest.md
- doc/README.md
- openapi/plantuml/schemas.plantuml
- organization/src/main/openapi/organization.yaml
- solution/src/integrationTest/kotlin/com/cosmotech/solution/service/SolutionServiceIntegrationTest.kt
- solution/src/main/kotlin/com/cosmotech/solution/service/SolutionServiceImpl.kt
- solution/src/main/openapi/solution.yaml
- workspace/src/main/kotlin/com/cosmotech/workspace/service/WorkspaceServiceImpl.kt
This branch contains:
- Run SolutionControllerTests and WorkspaceControllerTests in build_test_package workflow
- Mvc tests and Spring RestDocs associated for Workspace and Solution modules
- Mvc tests Code cleaning
> Mvc tests for workspace solution

- api/src/integrationTest/kotlin/com/cosmotech/api/home/ControllerTestUtils.kt
- api/src/integrationTest/kotlin/com/cosmotech/api/home/solution/SolutionConstants.kt
- api/src/integrationTest/kotlin/com/cosmotech/api/home/solution/SolutionControllerTests.kt
- dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceIntegrationTest.kt
- doc/Models/Solution.md
- doc/Models/SolutionCreateRequest.md
- doc/Models/SolutionUpdateRequest.md
- openapi/plantuml/schemas.plantuml
- runner/src/integrationTest/kotlin/com/cosmotech/runner/service/RunnerServiceIntegrationTest.kt
- runner/src/integrationTest/kotlin/com/cosmotech/runner/service/RunnerServiceRBACTest.kt
- solution/src/integrationTest/kotlin/com/cosmotech/solution/service/SolutionServiceIntegrationTest.kt
- solution/src/integrationTest/kotlin/com/cosmotech/solution/service/SolutionServiceRBACTest.kt
- solution/src/main/kotlin/com/cosmotech/solution/service/SolutionServiceImpl.kt
- solution/src/main/openapi/solution.yaml
- workspace/src/integrationTest/kotlin/com/cosmotech/workspace/service/WorkspaceServiceIntegrationTest.kt
- workspace/src/integrationTest/kotlin/com/cosmotech/workspace/service/WorkspaceServiceRBACTest.kt
The field is now read only and is 'computed' at runtime from a label on the docker image.
This requires the solution image heving been built with a SDK version 11.3.0 or newer, but it should be relatively easy to manually add the required label ('com.cosmotech.sdk-version') with older SDK version
> [PROD-13446] Solution.sdkVersion is now retrieved from the docker image

- api/src/integrationTest/kotlin/com/cosmotech/api/home/ControllerTestUtils.kt
- api/src/integrationTest/kotlin/com/cosmotech/api/home/run/RunControllerTests.kt
- api/src/integrationTest/kotlin/com/cosmotech/api/home/runner/RunnerControllerTests.kt
- api/src/integrationTest/kotlin/com/cosmotech/api/home/solution/SolutionControllerTests.kt
- build.gradle.kts
- dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceIntegrationTest.kt
- doc/.openapi-generator/FILES
- doc/Apis/SolutionApi.md
- doc/Models/RunTemplate.md
- doc/Models/SolutionCreateRequest.md
- doc/Models/SolutionUpdateRequest.md
- doc/README.md
- openapi/plantuml/schemas.plantuml
- run/src/integrationTest/kotlin/com/cosmotech/run/service/RunServiceIntegrationTest.kt
- run/src/test/kotlin/com/cosmotech/run/ContainerFactoryTests.kt
- runner/src/integrationTest/kotlin/com/cosmotech/runner/service/RunnerServiceIntegrationTest.kt
- runner/src/integrationTest/kotlin/com/cosmotech/runner/service/RunnerServiceRBACTest.kt
- solution/src/integrationTest/kotlin/com/cosmotech/solution/service/SolutionServiceIntegrationTest.kt
- solution/src/integrationTest/kotlin/com/cosmotech/solution/service/SolutionServiceRBACTest.kt
- solution/src/main/kotlin/com/cosmotech/solution/service/SolutionServiceImpl.kt
- solution/src/main/openapi/solution.yaml
- workspace/src/integrationTest/kotlin/com/cosmotech/workspace/service/WorkspaceServiceIntegrationTest.kt
- workspace/src/integrationTest/kotlin/com/cosmotech/workspace/service/WorkspaceServiceRBACTest.kt
- workspace/src/test/kotlin/com/cosmotech/workspace/service/WorkspaceServiceImplTests.kt
You can now update solution runTemplates via solution update endpoint (/organizations/{organization_id}/solutions/{solution_id}.
Now, If no run Template is specified when a solution update is requested, solution will have empty runTemplates property after update.
As we allowed runTemplates property to be updated when a solution is updated, we added CRUD endpoints for solution runTemplates to manage this property easily:
- GET /organizations/{organization_id}/solutions/{solution_id}/runTemplates
- POST /organizations/{organization_id}/solutions/{solution_id}/runTemplates
- GET /organizations/{organization_id}/solutions/{solution_id}/runTemplates/{parameter_group_id}
- PATCH /organizations/{organization_id}/solutions/{solution_id}/runTemplates/{parameter_group_id}
- DELETE …
> Add crud on solution run templates

- doc/Models/SolutionUpdateRequest.md
- solution/src/integrationTest/kotlin/com/cosmotech/solution/service/SolutionServiceIntegrationTest.kt
- solution/src/main/kotlin/com/cosmotech/solution/service/SolutionServiceImpl.kt
- solution/src/main/openapi/solution.yaml
- Remove default property alwaysPull in SolutionUpdateRequest
- fix update mechanism for runTemplates/parameters/parameterGroups on updateSolution
> Fix updateSolution with empty SolutionUpdateRequest

- sonar-project.properties
Select directories to be excluded from SonarQube analysis
> feat: configure static code analyzer

- build.gradle.kts
At this point, I don't know why we get this error. Everything looks great and accessible in mvnrepository especially kotlin library. But we do have the following error:
```
Could not resolve org.jetbrains.kotlin:kotlin-test:1.9.23.
Required by:
project :cosmotech-connector-api
> Unable to find a variant of org.jetbrains.kotlin:kotlin-test:1.9.23 providing the requested capability org.jetbrains.kotlin:kotlin-test-framework-junit5:
```
Upgrading kotlin version to 1.9.25 will force the kotlin-test module's version to 1.9.25 too and it apparently fixes the compilation error message...
> Fix "Could not resolve org.jetbrains.kotlin:kotlin-test:1.9.23"

- .github/workflows/lint.yml
Uploading merged reports for the same build and tool is not supported on Github anymore
See https://github.blog/changelog/2024-05-06-code-scanning-will-stop-combining-runs-from-a-single-upload/
> Upload detekt's SARIF reports one by one

- README.md
- build.gradle.kts
- common/src/main/kotlin/com/cosmotech/common/config/CsmApiConfiguration.kt
- common/src/main/kotlin/com/cosmotech/common/config/CsmPlatformProperties.kt
- common/src/test/kotlin/com/cosmotech/common/rbac/CsmRbacTests.kt
- run/src/main/kotlin/com/cosmotech/run/RunContainerFactory.kt
- run/src/test/kotlin/com/cosmotech/run/ContainerFactoryTests.kt
- Eliminated `vendor` from `CsmPlatformProperties` and related configurations.
- Removed `identityProvider.code` from platform properties and associated usages in tests, configs, and runtime environments.
- Refactored environment profiles.
> Remove vendor and identity provider code properties
